spring:
  application:
    name: steel-frame
  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: logs/app.log
  level:
    root: info
    io.github.renatoconrado: info
    org.springframework:
      web: info
      security: trace
  pattern:
    console: '%clr(%d{dd-mm HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'

management:
  server:
    port: 9090
